def creation_fichier():
 with open("param.py", "w+") as var:
#  var.write("from GenerationCode import *\n")
  var.write("from pyfirmata import Arduino, util\n")
  var.write("import time\n")
  var.write("def param():\n")
  var.write(" board = Arduino('COM7')\n")
  var.write(" test = True\n")
  var.write(" i=0\n")
  var.write(" led = []\n")
  var.write(" for m in range (2, 12):\n")
  var.write("   led.append(board.get_pin('d:' +str(m)+ ':o'))\n")
  var.write(" choix_affichage = 0\n")
  var.write(" choix = 0\n")
  var.write(" for n in range(2, 12):\n")
  var.write("   choix_affichage = int(input('Choix numero : '))\n")
  var.write("   print('Vous avez choisi l affichage :', choix_affichage)\n")
  var.write("   if choix_affichage == 1:\n")
  var.write("     while True:\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(1)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         led[i].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+2\n")
  var.write("   if choix_affichage == 2:\n")
  var.write("     while True:\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(1)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         led[i].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+3\n")
  var.write("   if choix_affichage == 3:\n")
  var.write("     while True:\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(1)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         led[i].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+4\n")
  var.write("   if choix_affichage == 4:\n")
  var.write("     while True:\n")
  var.write("       choix = int(input('Entrer le chiffre de la LED souhaitee'))\n")
  var.write("       print('Vous avez choisi la LED : ', choix)\n")
  var.write("       if choix > 10 or choix < 1:\n")
  var.write("         print('Error')\n")
  var.write("         print('S il vous plait bien vouloir choisir une LED comprise entre 1 et 10')\n")
  var.write("       else:\n")
  var.write("         while True:\n")
  var.write("           led[choix].write(1)\n")
  var.write("           time.sleep(1)\n")
  var.write("           led[choix].write(0)\n")
  var.write("           time.sleep(1)\n")
  var.write("   if choix_affichage == 5:\n")
  var.write("     while True:\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(1)\n")
  var.write("         time.sleep(0.03)\n")
  var.write("         led[i+1].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         led[i].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         led[i+1].write(1)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+1\n")
  var.write("   if choix_affichage == 6:\n")
  var.write("     while True:\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(1)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+1\n")
  var.write("       for i in range(2,12):\n")
  var.write("         led[i].write(0)\n")
  var.write("         time.sleep(0.5)\n")
  var.write("         i+1\n")

  var.write("   board.exit()\n")


def main():
 creation_fichier()
 print("Le fichier param.py a bel et bien ete cree")

main()
creation_fichier()


